<?php
/**
 * @var $post \Ecommage\HelloWorld\Model\Post
 */
echo 'hello world';
?>
<!-- Swiper -->
<div class="swiper-container">
    <div class="swiper-wrapper">
        <?php foreach ($block->getPostCollection() as $post){

            ?>
            <div class="swiper-slide">
                <img src="<?php echo $post->getImageUrl().$post->getFeaturedImage();  ?>" style="width: 100px;">
                <div><?php echo $post->getName(); ?></div>
                <div class="toggle"><?php echo $post->getPostContent(); ?></div>
<!--                <button class="toggle">Show/Hidden</button>-->
            </div>
       <?php } ?>


    </div>

    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>

<!--    <div>--><?php //echo $block->getUrl('helloworld/index/ajax'); ?><!--</div>-->
</div>
<form id="show">
    <input type="hidden" name="current_page" value="1"/>
    <input type="submit" value="Load more">
</form>
<!-- Swiper JS -->

<script>
    require(['jquery','swiper'], function($, Swipper) {
        var swiper = new Swipper('.swiper-container', {
            slidesPerView: 3,
            spaceBetween: 30,
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
            }
        });
    });
    require(['jquery'], function($){
        $data = $('#show').serialize()
        // console.log($data);
        $("input").click(function(event){
            event.preventDefault();
            $.ajax({
                method: "POST",
                data: $data,
                url: "<?php  echo $block->getUrl('helloworld/index/ajax'); ?>",
                // data: { 'isAjax' => 'true',
                //         'current_page'    => $('[name="current_page"]').val()
                // },
                dataType: "json"
                }).done(function( res ){

                    if (res.status == 'OK') {
                        var content = $(res.content).find('.swiper-wrapper').html();
                        $('.swiper-wrapper').append(content);
                        $('[name="current_page"]').val(res.current_page);
                    }
            });
        });
    });
</script>